### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by PokiShino** [FogNetwork/Rusty#1]
Normally RUSTY did work but then suddenly after November 28th (when you made changes to index.js), something happened and now it does not work. I go to the proxy I search it up and it loads. However, on youtube let's say, it says something went wrong please try reloading. Same thing on SoundCloud and many other websites that worked before you changed it.

**Comment by Nebelung-Dev** [comment]
Just tried youtube and it works. It might me a problem with your internet

**Comment by Nebelung-Dev** [comment]
Should be fixed
